### ISSUE TITLE
plugin messes with hex colors

### ISSUE THREAD

**Issue by GitNether** [festino-mc-plugins/ClickableLinks#2]
![image_2024-03-06_045156959](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/e93ef90d-0042-4ea8-8c22-b1138d035786)

I've used this code in my server to translate hex codes, maybe you are able to reuse it. Then we'd be able to use your plugin again :)

```java
public String translateHexColorCodes(String startTag, String endTag, String message)
    {
        final Pattern hexPattern = Pattern.compile(startTag + "([A-Fa-f0-9]{6})" + endTag);
        Matcher matcher = hexPattern.matcher(message);
        StringBuffer buffer = new StringBuffer(message.length() + 4 * 8);
        while (matcher.find())
        {
            String group = matcher.group(1);
            matcher.appendReplacement(buffer, COLOR_CHAR + "x"
                    + COLOR_CHAR + group.charAt(0) + COLOR_CHAR + group.charAt(1)
                    + COLOR_CHAR + group.charAt(2) + COLOR_CHAR + group.charAt(3)
                    + COLOR_CHAR + group.charAt(4) + COLOR_CHAR + group.charAt(5)
            );
        }
        return matcher.appendTail(buffer).toString();
    }
```

**Comment by festino** [comment]
Could you please tell me which color chat plugin you are using so I can easily reproduce?

**Comment by GitNether** [comment]
We're using EssentialsX.

Also, if you have a colored message, the link resets the color, and the message after it turns white. Maybe there is an easy way around that, just wanted to mention it.

**Comment by GitNether** [comment]
Another idea I had, which would probably be fairly easy to add since you already have the structure going on:

If there is a command in the message such as ./cmd or /cmd, you could make that clickable aswell to execute the command directly. Arguments could be added using smth like /cmd_arg1_arg2 to prevent it to interfere with the sentence (just as an idea I had).

**Comment by festino** [comment]
As a player with an underscore in my nickname, I would prefer not to use "_". The idea itself is not bad, you can open a feature request. =)

**Comment by festino** [comment]
Update: there was an incorrect assumption that color characters can only be in the format string. I need to implement style preserversion, so the fix will take some more time.

**Comment by festino** [comment]
I believe I fixed it with ac9fe05, but I will test it properly before releasing.

**Comment by GitNether** [comment]
If you release it, I'll test it on our server :)

**Comment by festino** [comment]
I have published a fix in the new release:
https://github.com/festino-mc-plugins/ClickableLinks/releases/tag/v1.2.0
Check if the issue is gone. =)

**Comment by GitNether** [comment]
Hmmm.. seems like something else is still messing with the colors
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/63342db2-50ff-47d2-bb6a-392a136b1556)

**Comment by festino** [comment]
Ohhh
I think I have added hex support for messages but not for nicknames 😅
Fortunately, now it’s easy to add this too.

**Comment by festino** [comment]
I believe it is fixed now
https://github.com/festino-mc-plugins/ClickableLinks/releases/tag/v1.2.1
(I should request more information to reproduce, in the future)
UPD. Will fix prefixes and postfixes soon

**Comment by GitNether** [comment]
Bad news
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/e330af04-940e-462b-b5b6-be61388fee35)

**Comment by festino** [comment]
Sorry for release flooding
https://github.com/festino-mc-plugins/ClickableLinks/releases/tag/v1.2.2

**Comment by GitNether** [comment]
Colors work! :D 
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/e5bf5417-8e40-4a4c-957d-4ece39680a9a)

but bold is gone :o

**Comment by GitNether** [comment]
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/3caa9c8b-525c-4240-868c-9cbdffe4a383)
Also a funny bug

**Comment by festino** [comment]
Could you tell if any formatting (bold, etc) is currently working anywhere with the plugin?

**Comment by GitNether** [comment]
In the message it works
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/3070bb9c-cf18-4644-83f9-778fae4fb6a5)

**Comment by GitNether** [comment]
any formatting turns purple though ^ i didnt put any color

**Comment by festino** [comment]
Oh, I see. Color codes should be inserted before formatting codes

**Comment by festino** [comment]
> ![image](https://private-user-images.githubusercontent.com/100975664/313410249-3caa9c8b-525c-4240-868c-9cbdffe4a383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTk0NjAsIm5iZiI6MTcxMDU5OTE2MCwicGF0aCI6Ii8xMDA5NzU2NjQvMzEzNDEwMjQ5LTNjYWE5YzhiLTUyNWMtNDI0MC04NjhjLTljYmRmZmU0YTM4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDI2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Nzc0NjA3ZDMzYjBlZjk4MGI0NDFkYTQ4ZDA3M2NhNGFlZjUyMmFiZmMyZWQ4MWNjM2E3ZmJiZjJjZGVmNjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LXCBg7y-ledj2I0sXVwTnYALRK4qp7Q3HAKAfZI6RZY) Also a funny bug

I don't understand what is going on.
When I send "&4hello google.com 12345", extra "4" does not appear

**Comment by festino** [comment]
I have updated v1.2.2 jar, formatting is fixed
https://github.com/festino-mc-plugins/ClickableLinks/releases/tag/v1.2.2

**Comment by GitNether** [comment]
Still no bold on my end, weirdly enough

**Comment by festino** [comment]
Could you temporarily enable "/links log-debug-info true" and copy-paste raw JSON of the message?

**Comment by GitNether** [comment]
&4 1234 google.com 1234 produced these two:

16.03 15:36:56 [Server] [INFO] [ClickableLinks] Sending raw JSON: [{"color":"#8701ff","text":"<"},{"color":"#fbf896","text":"★"},{"color":"#9062fe","text":"I"},{"color":"#aa87f7","text":"X"},{"color":"#fbf895","text":"★"},{"color":"#8701ff","text":"> "},{"color":"#FF0000","text":"["},{"color":"#E70505","text":"A"},{"color":"#CF0909","text":"D"},{"color":"#B70E0E","text":"M"},{"color":"#9F1313","text":"I"},{"color":"#871717","text":"N"},{"color":"#6F1C1C","text":"] "},{"color":"#fdfbff","text":"["},{"color":"#bf6bff","text":"I Voted✔"},{"color":"#fdfbff","text":"] "},{"color":"#240000","text":"N"},{"color":"#480000","text":"e"},{"color":"#6d0000","text":"t"},{"color":"#910000","text":"h"},{"color":"#b60000","text":"e"},{"color":"#da0000","text":"r"},{"color":"#fe0000","text":". "},{"text":"§7➣"},{"text":"§f "},[{"text":"§41234 "},{"text":"§4§ngoogle.com","clickEvent":{"action":"open_url","value":"https://google.com"}},{"text":"§4 1234"}]]
16.03 15:36:56 [Server] [INFO] [ClickableLinks] Sending raw JSON: [{"color":"#8701ff","text":"<"},{"color":"#fbf896","text":"★"},{"color":"#9062fe","text":"I"},{"color":"#aa87f7","text":"X"},{"color":"#fbf895","text":"★"},{"color":"#8701ff","text":"> "},{"color":"#FF0000","text":"["},{"color":"#E70505","text":"A"},{"color":"#CF0909","text":"D"},{"color":"#B70E0E","text":"M"},{"color":"#9F1313","text":"I"},{"color":"#871717","text":"N"},{"color":"#6F1C1C","text":"] "},{"color":"#fdfbff","text":"["},{"color":"#bf6bff","text":"I Voted✔"},{"color":"#fdfbff","text":"] "},{"color":"#240000","text":"N"},{"color":"#480000","text":"e"},{"color":"#6d0000","text":"t"},{"color":"#910000","text":"h"},{"color":"#b60000","text":"e"},{"color":"#da0000","text":"r"},{"color":"#fe0000","text":". "},{"text":"§7➣"},{"text":"§f "},[{"text":"§41234 "},{"text":"§4§ngoogle.com","clickEvent":{"action":"open_url","value":"https://google.com"}},{"text":"§4 1234"}]]

**Comment by festino** [comment]
Yeah, this is weird. Not a single bold code "§l"
Also, is it still "hello google.com**4** 12345" in the chat?

**Comment by GitNether** [comment]
Yep, still the extra 4 and wrong colouring weirdly enough
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/ee529dbd-031c-4b0f-9e52-bfec6edf70f5)

**Comment by festino** [comment]
I will try to reproduce and fix it tomorrow

**Comment by festino** [comment]
I found another bug: the first style after any hex color was disappearing. I believe that is why bold was gone
As before, I updated .jar:
https://github.com/festino-mc-plugins/ClickableLinks/releases/tag/v1.2.2

**Comment by GitNether** [comment]
Color still buggy, but Bold works! :D
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/3f810256-0ce2-4cda-9bf7-e9531e2fadb1)

**Comment by festino** [comment]
Can you give me a minimal reproducible example? I could not reproduce the color bug
Also, are you using Spigot or some other server core?

**Comment by GitNether** [comment]
Yes, Spigot.
It seems like it only happens if there is a number after the link
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/1867b0cd-3e33-437c-9b68-42031106b021)

**Comment by festino** [comment]
I couldn't come up with a message format that would reproduce "extra 4" bug, but I did reproduce the color bug. I hope it is fixed now:
https://github.com/festino-mc-plugins/ClickableLinks/releases/tag/v1.2.2

**Comment by GitNether** [comment]
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/58789bbf-a33c-46f5-9e64-323d59d7e410)
Weirdly still happens. The link resets the color, but only if theres numbers directly after, which is weird.
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/52833020-f1cf-41ff-84b0-0bd063933781)

**Comment by GitNether** [comment]
Other than that it's looking fine, so thank you!

**Comment by GitNether** [comment]
Oh i just found this funny bug! Might help
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/5a786b4b-17cb-4291-b139-1cfc9eaa0579)

**Comment by GitNether** [comment]
seems like the ampersand & is missing.

**Comment by festino** [comment]
Again, I couldn't reproduce this. For the latest bug fixes I used (/plugins/Essentials/config.yml):
format: '&r&#00FF00&l<&7&l<&r<{DISPLAYNAME}&r&l&#00FF00>&l&7>&r> &3{MESSAGE}'
I would like to get your format or minimal reproducible example to fix this

**Comment by GitNether** [comment]
Our current format: '{PREFIX} {deluxetags_tag} &r{NICKNAME} &7➣&f {MESSAGE}'

**Comment by festino** [comment]
format: '{PREFIX} &r{DISPLAYNAME} &7➣&f {MESSAGE}'
T-T
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/44211685/fd067eab-ebe2-4646-b9ac-62dc3c83c075)
My configuration:
* Minecraft 1.20.1 (both vanilla and modded client)
* 3871-Spigot-d2eba2c-3f9263b
* EssentialsX v2.21.0-dev+73-2cb0af0
* EssentialsChat v2.21.0-dev+73-2cb0af0
* ClickableLinks v1.2.2
* No other plugins

**Comment by GitNether** [comment]
That's so weird lol
![image](https://github.com/festino-mc-plugins/ClickableLinks/assets/100975664/27b807d4-5723-4db5-9e26-d56d03b33377)
EssentialsX and Chat 2.20.1

We're using Paper, but thats fundamentally Spigot too.

**Comment by festino** [comment]
I have no idea how can it be. I set up a server from scratch:
Paper-196
EssentialsX and Chat 2.20.1
ClickableLinks 1.2.2
+used vanilla 1.20.1 client with default settings. I gave myself an op to get color permission.

Neither the default format nor '{PREFIX} &r{DISPLAYNAME} &7➣&f {MESSAGE}' could reproduce the bug

**Comment by GitNether** [comment]
Damn that's really weird. Some other plugin then must interfere with it, I suppose.
Well, the main issue is fixed, and links are working properly now, so thank you for that and we can close this ticket finally!

**Comment by festino** [comment]
Ok. But I just want to polish the plugin: if you find any clues, then open a new ticket :)
